### ISSUE TITLE
Test app does not run

### ISSUE THREAD

**Issue by Isaac12x** [electrode-samples/electrode-progressive-beer#36]
Following the README.md instructions and substituting sever by start I get the following error which seems to be related to the server configuration:

```bash
[16:53:41] Starting 'app-server'...
Just FYI: There's a new src/lib mode that doesn't need babel-register.
 > isomorphic-loader extend require: config is not ready - waiting for config file to be generated. <
 > isomorphic-loader extend require: ERROR - unable to detect /Users/iamin/Downloads/electrode-progressive-beer-master/.isomorphic-loader-config.json
 >>>> If you are running with webpack dev server, please make sure that is working properly.
(node:76554) UnhandledPromiseRejectionWarning: Error: isomorphic-loader config not found
    at ExtendRequire.go (/Users/iamin/Downloads/electrode-progressive-beer-master/node_modules/isomorphic-loader/lib/extend-require.js:260:23)
    at Timeout._onTimeout (/Users/iamin/Downloads/electrode-progressive-beer-master/node_modules/isomorphic-loader/lib/extend-require.js:263:12)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
(node:76554) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:76554) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[16:53:58] Finished 'app-server' after 17 s
[16:53:58] Finished 'server' after 17 s
```

Any guidance on how to solve it?

**Comment by rajanikanth05** [comment]
Any update on this? I'm also getting the same issue.
